## Numpy Basics


Array of number 1-10

In [4]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)
print(arr.shape)
print(type(arr))

[ 1  2  3  4  5  6  7  8  9 10]
(10,)
<class 'numpy.ndarray'>


Create an array of 10 zeros and an array of 10 ones

In [12]:
zeros=np.zeros((3,10), int)
ones=np.ones((3,10), int)
sum=zeros+ones

print("Zeros: \n" , zeros)
print("Ones: \n", ones)
print("Sum: \n", sum)


Zeros: 
 [[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
Ones: 
 [[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]
Sum: 
 [[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


Multiply each elements

In [14]:
arr=np.array([5,10,15,20])
arr*2
print(arr)

[ 5 10 15 20]


Create a NumPy array from a Python list. Change its data type to float.

In [20]:
lst=[1,2,3,4]
arr1=np.array(lst,float)
print(arr1)


[1. 2. 3. 4.]


Indexing & slicing

In [30]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
#first 5 elements
print(f"First 5 elements: {arr[0:5]}")
print(f"Last 5 elements: {arr[10:]}")
print(f"Elements from 5-10: {arr[4:10]}")

First 5 elements: [1 2 3 4 5]
Last 5 elements: [11 12 13 14 15]
Elements from 5-10: [ 5  6  7  8  9 10]


In [32]:
# Only even numbers
print(arr[1:15:2])

[ 2  4  6  8 10 12 14]


In [34]:
arr[arr>10]=0
print(arr)

[ 1  2  3  4  5  6  7  8  9 10  0  0  0  0  0]


Aggregations

In [41]:
marks = np.array([78, 45, 92, 33, 60, 88, 41])
print(f"Maximum mark: {np.sum(marks)}")
print(f"Maximum mark: {np.max(marks)}")
print(f"Minimum mark: {np.min(marks)}")
print(f"Average: {np.mean(marks)}")

Maximum mark: 437
Maximum mark: 92
Minimum mark: 33
Average: 62.42857142857143


In [43]:
pass_count=np.sum(marks>=40)
fail_count=np.sum(marks<=40)

print(f"Passed: {pass_count}")
print(f"Failed: {fail_count}")

Passed: 6
Failed: 1


In [45]:
salary = np.array([18000, 25000, 12000, 40000])
bonus = np.where(salary < 20000,
                 salary * 0.20,
                 salary* 0.10)
print("Salaries:", salary)
print("Bonus:", bonus)


Salaries: [18000 25000 12000 40000]
Bonus: [3600. 2500. 2400. 4000.]


In [49]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])
print("Addition:", a+b)
print("Subtraction:", a-b)
print("Multiplication:", a*b)

Addition: [11 22 33 44]
Subtraction: [ -9 -18 -27 -36]
Multiplication: [ 10  40  90 160]


In [50]:
import numpy as np
sales = np.array([1200, 1500, 800, 2000, 1700])
total_sales = np.sum(sales)
avg_sales = np.mean(sales)
above_avg_days = sales[sales > avg_sales]
print("Total sales:", total_sales)
print("Average sales:", avg_sales)
print("Sales above average:", above_avg_days)


Total sales: 7200
Average sales: 1440.0
Sales above average: [1500 2000 1700]


In [54]:
scores = np.array([55, 72, 90, 48, 67])
grades = np.where(scores >= 85, 'A',
         np.where(scores >= 70, 'B',
         np.where(scores >= 50, 'C', 'F')))
print("Scores:", scores)
print("Grades:", grades)


Scores: [55 72 90 48 67]
Grades: ['C' 'B' 'A' 'F' 'C']


In [58]:
temp = np.array([32, 35, 30, 40, 38, 28])
max_temp=np.max(temp)
min_temp=np.min(temp)

print("Maximum Temperature:", max_temp)
print("Minimum Temperature:", min_temp)
print("The difference:", max_temp-min_temp)

Maximum Temperature: 40
Minimum Temperature: 28
The difference: 12
