In [1]:
import numpy as np


 Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [17]:
array=np.random.randint(1,21,size=(5,5))
array[:,3]=1
print(array)

[[ 4  3  3  1  2]
 [ 9 14 12  1 15]
 [ 5  8  3  1 20]
 [18 13  8  1  2]
 [14  5 17  1  4]]


Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [23]:
array=np.random.randint(1,17,size=(4,4))
np.fill_diagonal(array,0)
print(array)

[[ 0 13  2  7]
 [ 8  0  2 15]
 [ 2  4  0 11]
 [ 6 11 10  0]]


Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [36]:
arr=np.random.randint(1,36,size=(6,6))
sub_arr=arr[2:5,1:4]
print("Array: \n",arr)
print("Sub Array: \n" ,sub_arr)


Array: 
 [[20 35 24 24 34 11]
 [28 23 34 23 19 26]
 [15  2  6 31 31 22]
 [22  4 23  4 27 21]
 [14 12 18 17 20  4]
 [ 4 30 32 20 31 14]]
Sub Array: 
 [[ 2  6 31]
 [ 4 23  4]
 [12 18 17]]


Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [43]:
array = np.random.randint(1, 21, size=(5, 5))
print("Original array: \n",array)
border_elements = np.concatenate((array[0, :], array[-1, :], array[1:-1, 0], array[1:-1, -1]))
print("Border elements: \n",border_elements)


Original array: 
 [[ 2 12 10  5 15]
 [20 20 20 17  7]
 [14 15 16 13 13]
 [15 17  3 11 18]
 [12  4 10 12 16]]
Border elements: 
 [ 2 12 10  5 15 12  4 10 12 16 20 14 15  7 13 18]


Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [45]:
array1 = np.random.randint(1,5 , size=(3, 4))
array2 = np.random.randint(1,5 , size=(3, 4))
print("Original array1: \n", array1)
print("Original array2: \n", array2)

add_arr=array1+array2
sub_arr=array1-array2
mul_arr=array1*array2
div_arr=array1/array2
print("Addition: \n",add_arr)
print("Subtraction: \n",sub_arr)
print("Multiplication: \n",mul_arr)
print("Division: \n",div_arr)

Original array1: 
 [[3 2 4 2]
 [1 2 1 1]
 [2 3 4 2]]
Original array2: 
 [[2 3 1 2]
 [3 1 4 3]
 [1 2 1 1]]
Addition: 
 [[5 5 5 4]
 [4 3 5 4]
 [3 5 5 3]]
Subtraction: 
 [[ 1 -1  3  0]
 [-2  1 -3 -2]
 [ 1  1  3  1]]
Multiplication: 
 [[6 6 4 4]
 [3 2 4 3]
 [2 6 4 2]]
Division: 
 [[1.5        0.66666667 4.         1.        ]
 [0.33333333 2.         0.25       0.33333333]
 [2.         1.5        4.         2.        ]]


Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [46]:
arra = np.random.randint(1,16 , size=(4, 4))
row_sum=np.sum(arra, axis=1)
col_sum=np.sum(arra, axis=0)
print("Row wise sum: \n", row_sum)
print("column wise sum: \n", col_sum)

Row wise sum: 
 [26 38 30 25]
column wise sum: 
 [33 28 20 38]


Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [50]:
ar = np.random.randint(1,10 , size=(5, 5))
mean=np.mean(ar)
median = np.median(array)
std=np.std(ar)
var=np.var(ar)
print("Original array: \n", ar)
print("Mean: \n", mean)
print("Median: \n", median)
print("Standard Deviation: \n", std)
print("Variance: \n", var)

Original array: 
 [[3 3 4 6 3]
 [4 1 5 8 1]
 [2 9 4 7 3]
 [4 9 3 7 2]
 [2 8 3 1 9]]
Mean: 
 4.44
Median: 
 13.0
Standard Deviation: 
 2.6089078174592526
Variance: 
 6.8064


 Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [52]:
array = np.arange(1, 10).reshape((3, 3))
print("Original array: \n",array)
mean = np.mean(array)
std_dev = np.std(array)
normalized_array = (array - mean) / std_dev
print("Normalized array: \n",normalized_array)


Original array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized array: 
 [[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]
